###
POST http://localhost:8080/tabak/news-add
Content-Type: application/json

{
  "name": "Test",
  "short_description": "Test",
  "full_description": "Test",
  "news_type": 1
}

###
DELETE http://localhost:8080/tabak/news-delete/7

###
PUT http://localhost:8080/tabak/news-Update
Content-Type: application/json

{
  "id": 2,
  "name": "ttr",
  "short_description": "Test",
  "full_description": "Test",
  "news_type": 1
}