###
POST http://localhost:8080/tabak/news_type-add
Content-Type: application/json

{
  "name": "Weather",
  "color": "gray"
}

###
DELETE http://localhost:8080/tabak/news_type-delete/2

###
PUT http://localhost:8080/tabak/news_type-Update
Content-Type: application/json

{
  "id": 2,
  "name": "Football",
  "color": "blue"
}